version: "2.1"
services:
  image-ms:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      image-db:
        condition: service_healthy
    links:
    - image-db

  image-db:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli PING"
      interval: 20s
      retries: 10
